### ISSUE TITLE
has no attributes get_values()

### ISSUE THREAD

**Issue by deadmaus10** [jakeee51/gomaps#4]
Hello,

here is my code: 

from gomaps import maps_search

results = maps_search("autómosó magyarország")

results[0].get_values()

error log: 
Traceback (most recent call last):
  File "c:\Users\furim\Desktop\Google Maps Scrape\scrape", line 5, in <module>
    results[0].get_values()
AttributeError: 'str' object has no attribute 'get_values'

Could you please fix this?

**Comment by deadmaus10** [comment]
In the meantime I tried to print the raw results for my query, but for every query I use it returns the error message: __na_a

Could you please advice why I'm not getting results? 

Thanks a lot, appreciate your work a lot!

**Comment by jakeee51** [comment]
Greetings,

I was unable to reproduce this error. Try narrowing your search down, as it might be too general.

Also, there's no "__na_a" anywhere in the package's source code, so I'm unsure where that's coming from.

Try running this query instead:
`results = gomaps.maps_search("SPIwash Magyarország Kft., Budapest, Liberty Square Garage, Szabadság tér, 1054 Hungary")`

On another note, I've noticed that the _address_, _phone_number_, and _open_hours_ fields are failing to populate. I'll have to patch that when I get the chance.

**Comment by deadmaus10** [comment]
Hello Jakee,I’m sorry, I thought it would scrape down the whole query for a generic search.Indeed my fault, keep this going, you are awesome!Have a great day!Füri Martin+36 30 72 69 6012022. okt. 10. dátummal, 5:39 időpontban David Jake Morfe ***@***.***> írta:﻿
Greetings,
I was unable to reproduce this error. Try narrowing your search down, as it might be too general.
Also, there's no "__na_a" anywhere in the package's source code, so I'm unsure where that's coming from.
Try running this query instead:
results = gomaps.maps_search("SPIwash Magyarország Kft., Budapest, Liberty Square Garage, Szabadság tér, 1054 Hungary")
On another note, I've noticed that the address, phone_number, and open_hours fields are failing to populate. I'll have to patch that when I get the chance.

**Comment by fabioselau077** [comment]
Resolved? Same error, but the error `'str' object has no attribute 'get_values'` is because `results` return this string with error ("`GoogleMapsResults(['There are no local results matching your search!'])`")
